version: '2'
services:
  # Postgresql database
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=victorhad
      - POSTGRES_DB=tbl

  tbl:
    # Uses an image that's built from the Dockerfile in the dockers directory
    build: .
    # Name the image and insert a version
    image: tbl_image:2.0
    # Specify a custom container name.
    container_name: tbl
    # Set the secret_key to enviroment
    environment:
      - SECRET_KEY
      - CODACY_PROJECT_TOKEN
      - EMAIL_PASSWORD
    # Forwards the exposed port 8000 on the host machine to port 8000 on the container.
    ports:
      - '8000:8000'
    # Container dependencies
    depends_on:
      - db

  # Service
